name: Continuous Integration Documentation
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "api-docs/**"
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check And Build docs
        working-directory: api-docs/
        run: "./generate-docs.sh"

      - name: Clean git branch name
        uses: actions/github-script@v4
        id: set_branch
        with:
          script: |
            const ref_name = '${github.ref_name}'
            const head_ref = '${github.head_ref}'

            console.log(ref_name);
            console.log(head_ref);

            const branch = "bar"
            const cleanBranch = branch.replaceAll("/", "-")
            core.setOutput('value', cleanBranch)
        if: ${{github.ref_type == 'branch' && github.ref_name != 'main'}}

      # https://docs.narrative.io/open-api/my-feature
      - name: Publish to S3 based on the branch
        working-directory: api-docs/
        run: 'echo "generated-docs s3://narrative-cdn-docs/open-api/${{ steps.set_branch.outputs.value }}"'
        if: ${{github.ref_type == 'branch' && github.ref_name != 'main'}}

      - name: Get version from git tag
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const refTags = "refs/tags/"
            const tag = context.ref.substring(refTags)
            core.setOutput('value', tag)
        if: ${{github.ref_type == 'tag'}}

      # https://docs.narrative.io/open-api/1.2.3
      - name: Publish to S3 based on the tag
        working-directory: api-docs/
        run: 'echo "generated-docs s3://narrative-cdn-docs/open-api/${{ steps.set_version.outputs.value }}"'
        if: ${{github.ref_type == 'tag'}}
