name: Continuous Integration Documentation
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "api-docs/**"
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check And Build docs
        working-directory: api-docs/
        run: "./generate-docs.sh"

      - name: debug github
        run: "echo ${{ github }}"

      - name: debug github.ref_name
        run: "echo ${{ github.ref_name }}"

      - name: debug github.head_ref
        run: "echo ${{ github.head_ref }}"

      - name: debug github.base_ref
        run: "echo ${{ github.base_ref }}"

      - name: Publish S3 tags/branch
        working-directory: api-docs/
        run: 'echo "generated-docs s3://narrative-cdn-docs/open-api/${{ github.ref_name }}"'
        if: ${{github.ref_name != 'main'}}
