name: Continuous Integration Documentation
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "api-docs/**"
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check And Build docs
        working-directory: api-docs/
        run: "./generate-docs.sh"

      - name: Publish to S3 based on the branch
        working-directory: api-docs/
        run: 'echo "generated-docs s3://narrative-cdn-docs/open-api/${{ github.base_ref || github.ref_name }}"'
        if: ${{github.ref_type == 'branch' && github.ref_name != 'main'}}

      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)
        if: ${{github.ref_type == 'tag'}}

      - name: debug tag
        run: "echo ${{steps.set_version.outputs.tag}}"

      - name: debug no-v
        run: "echo ${{steps.set_version.outputs.no-v}}"

      - name: debug no-dash
        run: "echo ${{steps.set_version.outputs.no-dash}}"

      - name: Publish to S3 based on the tag
        working-directory: api-docs/
        run: 'echo "generated-docs s3://narrative-cdn-docs/open-api/${{ github.ref_name }}"'
        if: ${{github.ref_type == 'tag'}}
